version: '3.8'
services:
  command-handler:
    image: skisiel/news-scraping_command-handler:0.2
    # build: ./command-handler
    ports:
      - "5001:5001"
    networks:
      - scraper-network
    env_file:
      - command-handler/.env.prod

  scraper:
    image: skisiel/news-scraping_scraper:0.2
    # build: ./scraper
    ports:
      - "5002:5002"
    networks:
      - scraper-network
    volumes:
      - ./data:/application/data

  sentiment-analyser:
    image: skisiel/news-scraping_sentiment-analyser:0.2
    # build: ./sentiment-analyser
    ports:
      - "5003:5003"
    networks:
      - scraper-network

  sentiment-analyser-worker:
    image: skisiel/news-scraping_sentiment-analyser:0.2
    # build: ./sentiment-analyser
    entrypoint: celery
    command: -A celery_app worker --loglevel=info --pool=solo
    networks:
      - scraper-network
      
  scraper_db:
    image: mysql:8.0.31-debian
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./sql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd1
    networks:
      - scraper-network

  ui:
    image: skisiel/news-scraping_ui:0.2
    # build: ./frontend
    ports:
      - "8080:80"
    networks:
      - scraper-network

  redis:
    image: redis:7.0.7
    hostname: redis
    networks:
      - scraper-network

  rabbitmq:
    image: rabbitmq:3.11.6
    hostname: rabbitmq
    networks:
      - scraper-network

networks:
  scraper-network:
    name: custom_network
volumes:
  mysql:
  mysql_config: